<?php
// $Id: xoops_version.php,v 1.9 2004/09/27 16:57:22 phppp Exp $
//  ------------------------------------------------------------------------ //
//                        DIGEST for XOOPS                                   //
//             Copyright (c) 2004 Xoops China Community                      //
//                    <http://www.xoops.org.cn/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: D.J.(phppp) php_pp@hotmail.com                                    //
// URL: http://xoops.org.cn                                              //
// ------------------------------------------------------------------------- //
include_once(XOOPS_ROOT_PATH.'/modules/digest/include/vars.php');

$modversion['name'] = _MI_DIGEST_NAME;
$modversion['version'] = 2.01;
$modversion['description'] = _MI_DIGEST_DESC;
$modversion['credits'] = "WJUE(HTTP://WWW.WJUE.ORG), Karuna(http://ppfans.com).";
$modversion['author'] = "phppp (D.J.) ( http://xoops.org.cn/ )";
$modversion['help'] = "http://xoops.org.cn";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/digest.gif";
$modversion['dirname'] = "digest";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
$modversion['tables'][0] = "digest_digests";
$modversion['tables'][1] = "digest_categories";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['onInstall'] = 'include/functions.php';

// Templates
$modversion['templates'][1]['file'] = 'digest_index.html';
$modversion['templates'][1]['description'] = '';
//$modversion['templates'][2]['file'] = 'digest_custom.html';
//$modversion['templates'][2]['description'] = '';

// Blocks
$modversion['blocks'][1]['file'] = "digest_blocks.php";
$modversion['blocks'][1]['name'] = _MI_DIGEST_BLOCK_LIST;
$modversion['blocks'][1]['description'] = _MI_DIGEST_BLOCK_LIST_DESC;
$modversion['blocks'][1]['show_func'] = "b_digest_show";
$modversion['blocks'][1]['options'] = "list|2|60|30|2"; // block type|items from each digest|total items|item title length|columns
$modversion['blocks'][1]['edit_func'] = "b_digest_edit";
$modversion['blocks'][1]['template'] = 'digest_block_list.html';

$modversion['blocks'][2]['file'] = "digest_blocks.php";
$modversion['blocks'][2]['name'] = _MI_DIGEST_BLOCK_SCROLL;
$modversion['blocks'][2]['description'] = _MI_DIGEST_BLOCK_SCROLL_DESC;
$modversion['blocks'][2]['show_func'] = "b_digest_show";
$modversion['blocks'][2]['options'] = "scroll|2|60|30|200|10";  // block type|items from each digest|total items|item title length|scroll delay|scroll amount
$modversion['blocks'][2]['edit_func'] = "b_digest_edit";
$modversion['blocks'][2]['template'] = 'digest_block_scroll.html';

// Menu
$modversion['hasMain'] = 1;

// Config Settings (only for modules that need config settings generated automatically)
$modversion['config'][0]['name'] = 'title_length';
$modversion['config'][0]['title'] = '_MI_DIGEST_TITLELENGTH';
$modversion['config'][0]['description'] = '_MI_DIGEST_TITLELENGTH_DESC';
$modversion['config'][0]['formtype'] = 'textbox';
$modversion['config'][0]['valuetype'] = 'int';
$modversion['config'][0]['default'] = 30;

$modversion['config'][1]['name'] = 'two_column';
$modversion['config'][1]['title'] = '_MI_DIGEST_TWOCOLUMN';
$modversion['config'][1]['description'] = '_MI_DIGEST_TWOCOLUMN_DESC';
$modversion['config'][1]['formtype'] = 'yesno';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 1;

$modversion['config'][2]['name'] = 'allow_submit';
$modversion['config'][2]['title'] = '_MI_DIGEST_ALLOWSUBMIT';
$modversion['config'][2]['description'] = '_MI_DIGEST_ALLOWSUBMIT_DESC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 1;

$modversion['config'][3]['name'] = 'auto_approve';
$modversion['config'][3]['title'] = '_MI_DIGEST_AUTOAPPROVE';
$modversion['config'][3]['description'] = '_MI_DIGEST_AUTOAPPROVE_DESC';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 0;

$modversion['config'][4]['name'] = 'allow_upload';
$modversion['config'][4]['title'] = '_MI_DIGEST_ALLOWUPLOAD';
$modversion['config'][4]['description'] = '_MI_DIGEST_ALLOWUPLOAD_DESC';
$modversion['config'][4]['formtype'] = 'yesno';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;

$modversion['config'][10]['name'] = 'allowed_extension';
$modversion['config'][10]['title'] = '_MI_DIGEST_ALLOWEXTENSION';
$modversion['config'][10]['description'] = '_MI_DIGEST_ALLOWEXTENSION_DESC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'text';
$modversion['config'][10]['default'] = 'jpg|jpeg|gif|png';

$modversion['config'][5]['name'] = 'image_path';
$modversion['config'][5]['title'] = '_MI_DIGEST_IMAGEPATH';
$modversion['config'][5]['description'] = '_MI_DIGEST_IMAGEPATH_DESC';
$modversion['config'][5]['formtype'] = 'textbox';
$modversion['config'][5]['valuetype'] = 'text';
$modversion['config'][5]['default'] = 'uploads/digest';

$modversion['config'][6]['name'] = 'allow_custom';
$modversion['config'][6]['title'] = '_MI_DIGEST_ALLOWCUSTOM';
$modversion['config'][6]['description'] = '_MI_DIGEST_ALLOWCUSTOM_DESC';
$modversion['config'][6]['formtype'] = 'yesno';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 1;

$modversion['config'][7]['name'] = 'header';
$modversion['config'][7]['title'] = '_MI_DIGEST_HEADER';
$modversion['config'][7]['description'] = '_MI_DIGEST_HEADER_DESC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'text';
$modversion['config'][7]['default'] = '<h2>Digest</h2>';

$modversion['config'][8]['name'] = 'footer';
$modversion['config'][8]['title'] = '_MI_DIGEST_FOOTER';
$modversion['config'][8]['description'] = '_MI_DIGEST_FOOTER_DESC';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'text';
$modversion['config'][8]['default'] = '';


$modversion['releasedate'] = "May 15th 2005";
$modversion['status'] = "stable";
$modversion['TODO'] = "";

$modversion['author_website'][1]['url'] = "http://xoops.org.cn";
$modversion['author_website'][1]['name'] = "Xoops China";
$modversion['author_email'] = "php_pp@hotmail.com";
$modversion['demo_site_url'] = "http://xoops.org.cn/modules/digest";
$modversion['demo_site_name'] = "Xoops China";
$modversion['readme'] = XOOPS_URL."/modules/digest/readme.".$xoopsConfig['language'].".htm";
$modversion['support_site_url'] = "http://xoops.org.cn";
$modversion['support_site_name'] = "Xoops China";
$modversion['translator']= "";
$modversion['ack'] = "insraq - http://insraq.xoops.cn; clark from Xoops China <br />
To Mr Xoops: <br />
-- Kazumi Ono (onokazu) http://jp.xoops.org/ <br />
-- Goghs Cheng (goghs) http://www.eqiao.com/ <br />
";
?>